services:
    brille24_tier_price.tier_price_finder:
        class: Brille24\SyliusTierPricePlugin\Services\TierPriceFinder
        arguments:
            - '@brille24.repository.tierprice'

    brille24_tier_price.calculator.product_variant_price:
        class: Brille24\SyliusTierPricePlugin\Services\ProductVariantPriceCalculator
        decorates: sylius.calculator.product_variant_price
        arguments:
            - '@brille24_tier_price.calculator.product_variant_price.inner'
            - '@brille24_tier_price.tier_price_finder'

    brille24_tier_price.order_processing.order_prices_recalculator:
        class: Brille24\SyliusTierPricePlugin\Services\OrderPricesRecalculator
        decorates: sylius.order_processing.order_prices_recalculator
        arguments:
            - '@brille24_tier_price.calculator.product_variant_price'
