services:
  brille24_tierprice_tierprice_factory:
    class: Brille24\SyliusTierPricePlugin\Factory\TierPriceExampleFactory
    arguments: ['@sylius.repository.product_variant', '@sylius.repository.channel']
